<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function site_location_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.site_location':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Site Location module is a used to display Site location and the current time for the location in a predefined format as a block.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Display Time for different timezones with city and country.') . '</dt>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function site_location_theme($existing, $type, $theme, $path) {
  return [
    'site_location_block' => [
      'variables' => [
        'date' => NULL,
        'time' => NULL,
        'city' => NULL,
        'timezone_city' => NULL,
        'country' => NULL,
      ],
    ],
  ];
}
